let strip: neopixel.Strip = null
input.onButtonPressed(Button.AB, function () {
    basic.pause(200)
    music.playMelody("C5 B A G F E D C ", 200)
    maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 128)
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(2000)
    maqueen.writeLED(maqueen.LED.LEDRight, maqueen.LEDswitch.turnOn)
    maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 255)
    maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 255)
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    basic.pause(2000)
    maqueen.writeLED(maqueen.LED.LEDRight, maqueen.LEDswitch.turnOff)
    maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 255)
    maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 255)
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(2000)
    maqueen.writeLED(maqueen.LED.LEDLeft, maqueen.LEDswitch.turnOn)
    maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 255)
    maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 255)
    basic.pause(2000)
    maqueen.writeLED(maqueen.LED.LEDLeft, maqueen.LEDswitch.turnOff)
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
})
input.onButtonPressed(Button.B, function () {
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(200)
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(200)
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    basic.pause(200)
})
basic.forever(function () {
    basic.showIcon(IconNames.Happy)
    strip = neopixel.create(DigitalPin.P0, 4, NeoPixelMode.RGB)
})
